// Cloudflare POP location and region names from the official Status API.
// Source: https://www.cloudflarestatus.com/api/v2/components.json
// Retrieved 2026-10-03. Unknown/new POP codes remain usable without a mapping.
// Only the seven geographic groups are included; product components are omitted.
export const CLOUDFLARE_LOCATIONS: Readonly<
  Record<string, readonly [string, string]>
> = {
  ABJ: ["Abidjan, Ivory Coast", "Africa"],
  ACC: ["Accra, Ghana", "Africa"],
  ADD: ["Addis Ababa, Ethiopia", "Africa"],
  ADL: ["Adelaide, SA, Australia", "Oceania"],
  AGR: ["Agra, India", "Asia"],
  AMD: ["Ahmedabad, India", "Asia"],
  AKX: ["Aktobe, Kazakhstan", "Asia"],
  ABQ: ["Albuquerque, NM, United States", "North America"],
  ALG: ["Algiers, Algeria", "Africa"],
  ALA: ["Almaty, Kazakhstan", "Asia"],
  QWJ: ["Americana, Brazil", "Latin America & the Caribbean"],
  AMM: ["Amman, Jordan", "Middle East"],
  AMS: ["Amsterdam, Netherlands", "Europe"],
  ANC: ["Anchorage, AK, United States", "North America"],
  AAE: ["Annaba, Algeria", "Africa"],
  AVA: ["Anshun, China", "Asia"],
  TNR: ["Antananarivo, Madagascar", "Africa"],
  ARU: ["Aracatuba, Brazil", "Latin America & the Caribbean"],
  ARI: ["Arica, Chile", "Latin America & the Caribbean"],
  IAD: ["Ashburn, VA, United States", "North America"],
  NQZ: ["Astana, Kazakhstan", "Asia"],
  LLK: ["Astara, Azerbaijan", "Middle East"],
  ASU: ["Asunción, Paraguay", "Latin America & the Caribbean"],
  ATH: ["Athens, Greece", "Europe"],
  ATL: ["Atlanta, GA, United States", "North America"],
  AKL: ["Auckland, New Zealand", "Oceania"],
  AUS: ["Austin, TX, United States", "North America"],
  BGW: ["Baghdad, Iraq", "Middle East"],
  GYD: ["Baku, Azerbaijan", "Middle East"],
  BWN: ["Bandar Seri Begawan, Brunei", "Asia"],
  BLR: ["Bangalore, India", "Asia"],
  BKK: ["Bangkok, Thailand", "Asia"],
  BGR: ["Bangor, ME, United States", "North America"],
  XIY: ["Baoji, China", "Asia"],
  BCN: ["Barcelona, Spain", "Europe"],
  BAQ: ["Barranquilla, Colombia", "Latin America & the Caribbean"],
  BSR: ["Basra, Iraq", "Middle East"],
  BEY: ["Beirut, Lebanon", "Middle East"],
  BEL: ["Belém, Brazil", "Latin America & the Caribbean"],
  BEG: ["Belgrade, Serbia", "Europe"],
  CNF: ["Belo Horizonte, Brazil", "Latin America & the Caribbean"],
  TXL: ["Berlin, Germany", "Europe"],
  BBI: ["Bhubaneswar, India", "Asia"],
  FRU: ["Bishkek, Kyrgyzstan", "Asia"],
  BOG: ["Bogotá, Colombia", "Latin America & the Caribbean"],
  BOD: ["Bordeaux, France", "Europe"],
  BOS: ["Boston, MA, United States", "North America"],
  BSB: ["Brasilia, Brazil", "Latin America & the Caribbean"],
  BTS: ["Bratislava, Slovakia", "Europe"],
  BGI: ["Bridgetown, Barbados", "Latin America & the Caribbean"],
  BNE: ["Brisbane, QLD, Australia", "Oceania"],
  BRU: ["Brussels, Belgium", "Europe"],
  OTP: ["Bucharest, Romania", "Europe"],
  BUD: ["Budapest, Hungary", "Europe"],
  EZE: ["Buenos Aires, Argentina", "Latin America & the Caribbean"],
  CFC: ["Caçador, Brazil", "Latin America & the Caribbean"],
  CGY: ["Cagayan de Oro, Philippines", "Asia"],
  CAI: ["Cairo, Egypt", "Africa"],
  YYC: ["Calgary, AB, Canada", "North America"],
  CLO: ["Cali, Colombia", "Latin America & the Caribbean"],
  VCP: ["Campinas, Brazil", "Latin America & the Caribbean"],
  CAW: ["Campos dos Goytacazes, Brazil", "Latin America & the Caribbean"],
  CBR: ["Canberra, ACT, Australia", "Oceania"],
  CPT: ["Cape Town, South Africa", "Africa"],
  CEB: ["Cebu, Philippines", "Asia"],
  IXC: ["Chandigarh, India", "Asia"],
  CGD: ["Changde, China", "Asia"],
  CSX: ["Changsha, China", "Asia"],
  CZX: ["Changzhou, China", "Asia"],
  XAP: ["Chapeco, Brazil", "Latin America & the Caribbean"],
  CLT: ["Charlotte, NC, United States", "North America"],
  CTU: ["Chengdu, China", "Asia"],
  MAA: ["Chennai, India", "Asia"],
  CNX: ["Chiang Mai, Thailand", "Asia"],
  ORD: ["Chicago, IL, United States", "North America"],
  KIV: ["Chișinău, Moldova", "Europe"],
  CGP: ["Chittagong, Bangladesh", "Asia"],
  CKG: ["Chongqing, China", "Asia"],
  CHC: ["Christchurch, New Zealand", "Oceania"],
  CVG: ["Cincinnati, United States", "North America"],
  CLE: ["Cleveland, OH, United States", "North America"],
  CJB: ["Coimbatore, India", "Asia"],
  CMB: ["Colombo, Sri Lanka", "Asia"],
  CMH: ["Columbus, OH, United States", "North America"],
  CZL: ["Constantine, Algeria", "Africa"],
  CPH: ["Copenhagen, Denmark", "Europe"],
  COR: ["Córdoba, Argentina", "Latin America & the Caribbean"],
  CGB: ["Cuiaba, Brazil", "Latin America & the Caribbean"],
  CWB: ["Curitiba, Brazil", "Latin America & the Caribbean"],
  DAD: ["Da Nang, Vietnam", "Asia"],
  DKR: ["Dakar, Senegal", "Africa"],
  DLC: ["Dalian, China", "Asia"],
  DFW: ["Dallas, TX, United States", "North America"],
  DMM: ["Dammam, Saudi Arabia", "Middle East"],
  DAR: ["Dar Es Salaam, Tanzania", "Africa"],
  DPS: ["Denpasar, Indonesia", "Asia"],
  DEN: ["Denver, CO, United States", "North America"],
  DTW: ["Detroit, MI, United States", "North America"],
  DAC: ["Dhaka, Bangladesh", "Asia"],
  JIB: ["Djibouti City, Djibouti", "Africa"],
  DOH: ["Doha, Qatar", "Middle East"],
  DLA: ["Douala, Cameroon", "Africa"],
  DXB: ["Dubai, United Arab Emirates", "Middle East"],
  DUB: ["Dublin, Ireland", "Europe"],
  DUR: ["Durban, South Africa", "Africa"],
  RDU: ["Durham, NC, United States", "North America"],
  DYU: ["Dushanbe, Tajikistan", "Asia"],
  DUS: ["Düsseldorf, Germany", "Europe"],
  EBL: ["Erbil, Iraq", "Middle East"],
  FLN: ["Florianopolis, Brazil", "Latin America & the Caribbean"],
  FOR: ["Fortaleza, Brazil", "Latin America & the Caribbean"],
  FUO: ["Foshan, China", "Asia"],
  FRA: ["Frankfurt, Germany", "Europe"],
  FUK: ["Fukuoka, Japan", "Asia"],
  FOC: ["Fuzhou, China", "Asia"],
  GBE: ["Gaborone, Botswana", "Africa"],
  GVA: ["Geneva, Switzerland", "Europe"],
  GEO: ["Georgetown, Guyana", "Latin America & the Caribbean"],
  GYN: ["Goiânia, Brazil", "Latin America & the Caribbean"],
  GOT: ["Gothenburg, Sweden", "Europe"],
  GDL: ["Guadalajara, Mexico", "North America"],
  CAN: ["Guangzhou, China", "Asia"],
  GUA: ["Guatemala City, Guatemala", "Latin America & the Caribbean"],
  GYE: ["Guayaquil, Ecuador", "Latin America & the Caribbean"],
  KWE: ["Guiyang, China", "Asia"],
  GUM: ["Hagatna, Guam", "Oceania"],
  HFA: ["Haifa, Israel", "Middle East"],
  HAK: ["Haikou, China", "Asia"],
  YHZ: ["Halifax, Canada", "North America"],
  HAM: ["Hamburg, Germany", "Europe"],
  HAN: ["Hanoi, Vietnam", "Asia"],
  HRE: ["Harare, Zimbabwe", "Africa"],
  HEL: ["Helsinki, Finland", "Europe"],
  SJW: ["Hengshui, China", "Asia"],
  SGN: ["Ho Chi Minh City, Vietnam", "Asia"],
  HBA: ["Hobart, Australia", "Oceania"],
  HKG: ["Hong Kong", "Asia"],
  HNL: ["Honolulu, HI, United States", "North America"],
  IAH: ["Houston, TX, United States", "North America"],
  HYD: ["Hyderabad, India", "Asia"],
  IND: ["Indianapolis, IN, United States", "North America"],
  ISB: ["Islamabad, Pakistan", "Asia"],
  IST: ["Istanbul, Turkey", "Europe"],
  ADB: ["Izmir, Turkey", "Europe"],
  JAX: ["Jacksonville, FL, United States", "North America"],
  CGK: ["Jakarta, Indonesia", "Asia"],
  AIP: ["Jalandhar, India", "Asia"],
  BDQ: ["Jamnagar, India", "Asia"],
  JED: ["Jeddah, Saudi Arabia", "Middle East"],
  JXG: ["Jiaxing, China", "Asia"],
  TNA: ["Jinan, China", "Asia"],
  JNB: ["Johannesburg, South Africa", "Africa"],
  JHB: ["Johor Bahru, Malaysia", "Asia"],
  JOI: ["Joinville, Brazil", "Latin America & the Caribbean"],
  JDO: ["Juazeiro do Norte, Brazil", "Latin America & the Caribbean"],
  EBB: ["Kampala, Uganda", "Africa"],
  CNN: ["Kannur, India", "Asia"],
  KNU: ["Kanpur, India", "Asia"],
  MCI: ["Kansas City, MO, United States", "North America"],
  KHH: ["Kaohsiung City", "Asia"],
  KHI: ["Karachi, Pakistan", "Asia"],
  KTM: ["Kathmandu, Nepal", "Asia"],
  KGL: ["Kigali, Rwanda", "Africa"],
  KIN: ["Kingston, Jamaica", "North America"],
  FIH: ["Kinshasa, DR Congo", "Africa"],
  COK: ["Kochi, India", "Asia"],
  CCU: ["Kolkata, India", "Asia"],
  KUL: ["Kuala Lumpur, Malaysia", "Asia"],
  KCH: ["Kuching, Malaysia", "Asia"],
  KMG: ["Kunming, China", "Asia"],
  KWI: ["Kuwait City, Kuwait", "Middle East"],
  KBP: ["Kyiv, Ukraine", "Europe"],
  LPB: ["La Paz, Bolivia", "Latin America & the Caribbean"],
  LOS: ["Lagos, Nigeria", "Africa"],
  LHE: ["Lahore, Pakistan", "Asia"],
  PKX: ["Langfang, China", "Asia"],
  LHW: ["Lanzhou, China", "Asia"],
  LAS: ["Las Vegas, NV, United States", "North America"],
  LLW: ["Lilongwe, Malawi", "Africa"],
  LIM: ["Lima, Peru", "Latin America & the Caribbean"],
  LIS: ["Lisbon, Portugal", "Europe"],
  LJU: ["Ljubljana, Slovenia", "Europe"],
  LHR: ["London, United Kingdom", "Europe"],
  LAX: ["Los Angeles, CA, United States", "North America"],
  LAD: ["Luanda, Angola", "Africa"],
  LUH: ["Ludhiana, India", "Asia"],
  LYA: ["Luoyang, China", "Asia"],
  LUN: ["Lusaka, Zambia", "Africa"],
  LUX: ["Luxembourg City, Luxembourg", "Europe"],
  LYS: ["Lyon, France", "Europe"],
  MFM: ["Macau", "Asia"],
  MAD: ["Madrid, Spain", "Europe"],
  MLG: ["Malang, Indonesia", "Asia"],
  MLE: ["Malé, Maldives", "Asia"],
  BAH: ["Manama, Bahrain", "Middle East"],
  MAO: ["Manaus, Brazil", "Latin America & the Caribbean"],
  MAN: ["Manchester, United Kingdom", "Europe"],
  MNL: ["Manila, Philippines", "Asia"],
  MPM: ["Maputo, Mozambique", "Africa"],
  MRS: ["Marseille, France", "Europe"],
  MDE: ["Medellín, Colombia", "Latin America & the Caribbean"],
  MEL: ["Melbourne, VIC, Australia", "Oceania"],
  MEM: ["Memphis, TN, United States", "North America"],
  MEX: ["Mexico City, Mexico", "North America"],
  MIA: ["Miami, FL, United States", "North America"],
  MXP: ["Milan, Italy", "Europe"],
  MSP: ["Minneapolis, MN, United States", "North America"],
  MSQ: ["Minsk, Belarus", "Europe"],
  MBA: ["Mombasa, Kenya", "Africa"],
  YUL: ["Montréal, QC, Canada", "North America"],
  DME: ["Moscow, Russia", "Europe"],
  BOM: ["Mumbai, India", "Asia"],
  MUC: ["Munich, Germany", "Europe"],
  MCT: ["Muscat, Oman", "Middle East"],
  NAG: ["Nagpur, India", "Asia"],
  OKA: ["Naha, Japan", "Asia"],
  NBO: ["Nairobi, Kenya", "Africa"],
  NJF: ["Najaf, Iraq", "Middle East"],
  BNA: ["Nashville, United States", "North America"],
  XNH: ["Nasiriyah, Iraq", "Middle East"],
  NQN: ["Neuquén, Argentina", "Latin America & the Caribbean"],
  DEL: ["New Delhi, India", "Asia"],
  EWR: ["Newark, NJ, United States", "North America"],
  LCA: ["Nicosia, Cyprus", "Europe"],
  ORF: ["Norfolk, VA, United States", "North America"],
  NOU: ["Noumea, New Caledonia", "Oceania"],
  OKC: ["Oklahoma City, OK, United States", "North America"],
  OMA: ["Omaha, NE, United States", "North America"],
  ORN: ["Oran, Algeria", "Africa"],
  KIX: ["Osaka, Japan", "Asia"],
  OSL: ["Oslo, Norway", "Europe"],
  OUA: ["Ouagadougou, Burkina Faso", "Africa"],
  PMO: ["Palermo, Italy", "Europe"],
  PMW: ["Palmas, Brazil", "Latin America & the Caribbean"],
  PTY: ["Panama City, Panama", "Latin America & the Caribbean"],
  PBM: ["Paramaribo, Suriname", "Latin America & the Caribbean"],
  CDG: ["Paris, France", "Europe"],
  PAT: ["Patna, India", "Asia"],
  PER: ["Perth, WA, Australia", "Oceania"],
  PHL: ["Philadelphia, United States", "North America"],
  PNH: ["Phnom Penh, Cambodia", "Asia"],
  PHX: ["Phoenix, AZ, United States", "North America"],
  PIT: ["Pittsburgh, PA, United States", "North America"],
  MRU: ["Port Louis, Mauritius", "Africa"],
  POS: ["Port of Spain, Trinidad and Tobago", "Latin America & the Caribbean"],
  PDX: ["Portland, OR, United States", "North America"],
  POA: ["Porto Alegre, Brazil", "Latin America & the Caribbean"],
  PRG: ["Prague, Czech Republic", "Europe"],
  PNQ: ["Pune, India", "Asia"],
  TAO: ["Qingdao, China", "Asia"],
  QRO: ["Queretaro, MX, Mexico", "North America"],
  UIO: ["Quito, Ecuador", "Latin America & the Caribbean"],
  ZDM: ["Ramallah", "Middle East"],
  REC: ["Recife, Brazil", "Latin America & the Caribbean"],
  KEF: ["Reykjavík, Iceland", "Europe"],
  RAO: ["Ribeirao Preto, Brazil", "Latin America & the Caribbean"],
  RIC: ["Richmond, VA, United States", "North America"],
  RIX: ["Riga, Latvia", "Europe"],
  GIG: ["Rio de Janeiro, Brazil", "Latin America & the Caribbean"],
  RUH: ["Riyadh, Saudi Arabia", "Middle East"],
  FCO: ["Rome, Italy", "Europe"],
  SMF: ["Sacramento, CA, United States", "North America"],
  LED: ["Saint Petersburg, Russia", "Europe"],
  RUN: ["Saint-Denis, Réunion", "Africa"],
  SLC: ["Salt Lake City, UT, United States", "North America"],
  SSA: ["Salvador, Brazil", "Latin America & the Caribbean"],
  JRG: ["Sambalpur, India", "Asia"],
  SAT: ["San Antonio, TX, United States", "North America"],
  SAN: ["San Diego, CA, United States", "North America"],
  SFO: ["San Francisco, CA, United States", "North America"],
  SJC: ["San Jose, CA, United States", "North America"],
  SJO: ["San José, Costa Rica", "Latin America & the Caribbean"],
  SJU: ["San Juan, Puerto Rico", "Latin America & the Caribbean"],
  SAP: ["San Pedro Sula, Honduras", "Latin America & the Caribbean"],
  MLA: ["Santa Venera, Malta", "Europe"],
  STI: [
    "Santiago de los Caballeros, Dominican Republic",
    "Latin America & the Caribbean",
  ],
  SCL: ["Santiago, Chile", "Latin America & the Caribbean"],
  SDQ: ["Santo Domingo, Dominican Republic", "Latin America & the Caribbean"],
  SJP: ["São José do Rio Preto, Brazil", "Latin America & the Caribbean"],
  SJK: ["São José dos Campos, Brazil", "Latin America & the Caribbean"],
  GRU: ["São Paulo, Brazil", "Latin America & the Caribbean"],
  YXE: ["Saskatoon, SK, Canada", "North America"],
  SEA: ["Seattle, WA, United States", "North America"],
  ICN: ["Seoul, South Korea", "Asia"],
  SHA: ["Shanghai, China", "Asia"],
  HGH: ["Shaoxing, China", "Asia"],
  SZX: ["Shenzhen, China", "Asia"],
  SIN: ["Singapore, Singapore", "Asia"],
  FSD: ["Sioux Falls, SD, United States", "North America"],
  SKP: ["Skopje, North Macedonia", "Europe"],
  SOF: ["Sofia, Bulgaria", "Europe"],
  SOD: ["Sorocaba, Brazil", "Latin America & the Caribbean"],
  GND: ["St. George's, Grenada", "Latin America & the Caribbean"],
  STL: ["St. Louis, MO, United States", "North America"],
  ARN: ["Stockholm, Sweden", "Europe"],
  STR: ["Stuttgart, Germany", "Europe"],
  ISU: ["Sulaymaniyah, Iraq", "Middle East"],
  URT: ["Surat Thani, Thailand", "Asia"],
  SUV: ["Suva, Fiji", "Oceania"],
  SYD: ["Sydney, NSW, Australia", "Oceania"],
  PPT: ["Tahiti, French Polynesia", "Oceania"],
  TPE: ["Taipei", "Asia"],
  HYN: ["Taizhou, China", "Asia"],
  TLH: ["Tallahassee, FL, United States", "North America"],
  TLL: ["Tallinn, Estonia", "Europe"],
  TPA: ["Tampa, FL, United States", "North America"],
  CRK: ["Tarlac City, Philippines", "Asia"],
  TBS: ["Tbilisi, Georgia", "Europe"],
  TGU: ["Tegucigalpa, Honduras", "Latin America & the Caribbean"],
  TLV: ["Tel Aviv, Israel", "Middle East"],
  SKG: ["Thessaloniki, Greece", "Europe"],
  PBH: ["Thimphu, Bhutan", "Asia"],
  NVT: ["Timbó, Brazil", "Latin America & the Caribbean"],
  TIA: ["Tirana, Albania", "Europe"],
  NRT: ["Tokyo, Japan", "Asia"],
  TEN: ["Tongren, China", "Asia"],
  YYZ: ["Toronto, ON, Canada", "North America"],
  TUN: ["Tunis, Tunisia", "Africa"],
  UDI: ["Uberlândia, Brazil", "Latin America & the Caribbean"],
  UDR: ["Udaipur, India", "Asia"],
  ULN: ["Ulaanbaatar, Mongolia", "Asia"],
  YVR: ["Vancouver, BC, Canada", "North America"],
  VIE: ["Vienna, Austria", "Europe"],
  VTE: ["Vientiane, Laos", "Asia"],
  VNO: ["Vilnius, Lithuania", "Europe"],
  VIX: ["Vitoria, Brazil", "Latin America & the Caribbean"],
  WAW: ["Warsaw, Poland", "Europe"],
  WLG: ["Wellington, New Zealand", "Oceania"],
  WDH: ["Windhoek, Namibia", "Africa"],
  YWG: ["Winnipeg, MB, Canada", "North America"],
  WRO: ["Wroclaw, Poland", "Europe"],
  XFN: ["Xiangyang, China", "Asia"],
  ACX: ["Xingyi, China", "Asia"],
  KHN: ["Xinyu, China", "Asia"],
  ASK: ["Yamoussoukro, Ivory Coast", "Africa"],
  TYN: ["Yangquan, China", "Asia"],
  EVN: ["Yerevan, Armenia", "Asia"],
  JOG: ["Yogyakarta, Indonesia", "Asia"],
  ZAG: ["Zagreb, Croatia", "Europe"],
  CGO: ["Zhengzhou, China", "Asia"],
  ZRH: ["Zurich, Switzerland", "Europe"],
};
